# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=140)),
                ('name', models.TextField()),
                ('symbol', models.CharField(max_length=140)),
                ('rank', models.IntegerField()),
                ('price_usd', models.IntegerField()),
                ('price_btc', models.IntegerField()),
                ('volume_usd_24h', models.IntegerField()),
                ('market_cap_usd', models.IntegerField()),
                ('available_supply', models.IntegerField()),
                ('total_supply', models.IntegerField()),
                ('max_supply', models.IntegerField()),
                ('percent_change_1h', models.IntegerField()),
                ('percent_change_24h', models.IntegerField()),
                ('percent_change_7d', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
