# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='history',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
