# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_post_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='available_supply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_updated',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='market_cap_usd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_supply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='percent_change_1h',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='percent_change_24h',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='percent_change_7d',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_btc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_usd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='rank',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='symbol',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_supply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='u_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='volume_usd_24h',
            field=models.TextField(),
        ),
    ]
